"""add Task, TaskAttempt, TaskEvent; task_id on approvals and cost_events

Revision ID: 6b1c524e1012
Revises: da1e9c017859
Create Date: 2026-08-21 10:55:58.762461

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b1c524e1012'
down_revision: Union[str, Sequence[str], None] = 'da1e9c017859'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('goal', sa.Text(), nullable=False),
    sa.Column('role', sa.String(length=120), nullable=False),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('allowed_resources', sa.JSON(), nullable=False),
    sa.Column('forbidden_actions', sa.JSON(), nullable=False),
    sa.Column('acceptance_criteria', sa.Text(), nullable=True),
    sa.Column('depends_on', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('timeout_seconds', sa.Integer(), nullable=True),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('budget_eur', sa.Float(), nullable=True),
    sa.Column('required_approvals', sa.JSON(), nullable=False),
    sa.Column('provider', sa.String(length=120), nullable=True),
    sa.Column('model', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_role'), 'tasks', ['role'], unique=False)
    op.create_index(op.f('ix_tasks_status'), 'tasks', ['status'], unique=False)
    op.create_table('task_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=120), nullable=True),
    sa.Column('model', sa.String(length=120), nullable=True),
    sa.Column('worktree_path', sa.String(length=500), nullable=True),
    sa.Column('branch', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('session_id', sa.String(length=200), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('files_changed', sa.JSON(), nullable=True),
    sa.Column('tests_passed', sa.Boolean(), nullable=True),
    sa.Column('cost_eur', sa.Float(), nullable=False),
    sa.Column('findings', sa.JSON(), nullable=True),
    sa.Column('blockers', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_attempts_task_id'), 'task_attempts', ['task_id'], unique=False)
    op.create_table('task_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('attempt_id', sa.Integer(), nullable=True),
    sa.Column('from_state', sa.String(length=30), nullable=True),
    sa.Column('to_state', sa.String(length=30), nullable=False),
    sa.Column('actor', sa.String(length=100), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['task_attempts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_events_attempt_id'), 'task_events', ['attempt_id'], unique=False)
    op.create_index(op.f('ix_task_events_task_id'), 'task_events', ['task_id'], unique=False)
    # batch_alter_table: SQLite can't ALTER a constraint onto an existing
    # table (only CREATE TABLE ... FOREIGN KEY at creation time), so adding
    # task_id + its FK to the already-existing approvals/cost_events tables
    # needs Alembic's copy-and-move batch mode here. On Postgres this same
    # block renders as a plain ALTER TABLE ADD COLUMN / ADD CONSTRAINT --
    # batch mode is a SQLite-only behavior change, not a schema difference.
    with op.batch_alter_table('approvals') as batch_op:
        batch_op.add_column(sa.Column('task_id', sa.Integer(), nullable=True))
        batch_op.create_index(op.f('ix_approvals_task_id'), ['task_id'], unique=False)
        batch_op.create_foreign_key('fk_approvals_task_id_tasks', 'tasks', ['task_id'], ['id'], ondelete='SET NULL')
    with op.batch_alter_table('cost_events') as batch_op:
        batch_op.add_column(sa.Column('task_id', sa.Integer(), nullable=True))
        batch_op.create_index(op.f('ix_cost_events_task_id'), ['task_id'], unique=False)
        batch_op.create_foreign_key('fk_cost_events_task_id_tasks', 'tasks', ['task_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cost_events') as batch_op:
        batch_op.drop_constraint('fk_cost_events_task_id_tasks', type_='foreignkey')
        batch_op.drop_index(op.f('ix_cost_events_task_id'))
        batch_op.drop_column('task_id')
    with op.batch_alter_table('approvals') as batch_op:
        batch_op.drop_constraint('fk_approvals_task_id_tasks', type_='foreignkey')
        batch_op.drop_index(op.f('ix_approvals_task_id'))
        batch_op.drop_column('task_id')
    op.drop_index(op.f('ix_task_events_task_id'), table_name='task_events')
    op.drop_index(op.f('ix_task_events_attempt_id'), table_name='task_events')
    op.drop_table('task_events')
    op.drop_index(op.f('ix_task_attempts_task_id'), table_name='task_attempts')
    op.drop_table('task_attempts')
    op.drop_index(op.f('ix_tasks_status'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_role'), table_name='tasks')
    op.drop_table('tasks')
    # ### end Alembic commands ###
